<html>
    <head>
        <title></title>
    </head>
	<link rel="stylesheet" href="assets/css/jQueryDatatables.css"
    <body>
    	<table id="empTable" class="cell-border">
    		<thead>
	    		<tr>
	    			<td>Id</td>
	    			<td>First Name</td>
	    			<td>Last Name</td>
	    			<td>10 %</td>
	    			<td>12 %</td>
	    			<td>Sal</td>
	    		</tr>
    		</thead>
    		<tbody>
	    		<tr>
		    		<td>1</td>
		    		<td>ABC</td>
		    		<td>DEF</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>70000</td>
	    		</tr>
	    		<tr>
		    		<td>2</td>
		    		<td>GHI</td>
		    		<td>JKL</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>90000</td>
	    		</tr>
	    		<tr>
		    		<td>3</td>
		    		<td>MNO</td>
		    		<td>PQR</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>7000</td>
	    		</tr>
	    		<tr>
		    		<td>4</td>
		    		<td>STU</td>
		    		<td>CWX</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>40000</td>
	    		</tr>
	    		<tr>
		    		<td>5</td>
		    		<td>YZ</td>
		    		<td>ABC</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>15000</td>
	    		</tr>
	    		<tr>
		    		<td>1</td>
		    		<td>ABC</td>
		    		<td>DEF</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>70000</td>
	    		</tr>
	    		<tr>
		    		<td>2</td>
		    		<td>GHI</td>
		    		<td>JKL</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>90000</td>
	    		</tr>
	    		<tr>
		    		<td>3</td>
		    		<td>MNO</td>
		    		<td>PQR</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>7000</td>
	    		</tr>
	    		<tr>
		    		<td>4</td>
		    		<td>STU</td>
		    		<td>CWX</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>40000</td>
	    		</tr>
	    		<tr>
		    		<td>5</td>
		    		<td>YZ</td>
		    		<td>ABC</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>15000</td>
	    		</tr><tr>
		    		<td>1</td>
		    		<td>ABC</td>
		    		<td>DEF</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>70000</td>
	    		</tr>
	    		<tr>
		    		<td>2</td>
		    		<td>GHI</td>
		    		<td>JKL</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>90000</td>
	    		</tr>
	    		<tr>
		    		<td>3</td>
		    		<td>MNO</td>
		    		<td>PQR</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>7000</td>
	    		</tr>
	    		<tr>
		    		<td>4</td>
		    		<td>STU</td>
		    		<td>CWX</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>40000</td>
	    		</tr>
	    		<tr>
		    		<td>5</td>
		    		<td>YZ</td>
		    		<td>ABC</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>15000</td>
	    		</tr><tr>
		    		<td>1</td>
		    		<td>ABC</td>
		    		<td>DEF</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>70000</td>
	    		</tr>
	    		<tr>
		    		<td>2</td>
		    		<td>GHI</td>
		    		<td>JKL</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>90000</td>
	    		</tr>
	    		<tr>
		    		<td>3</td>
		    		<td>MNO</td>
		    		<td>PQR</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>7000</td>
	    		</tr>
	    		<tr>
		    		<td>4</td>
		    		<td>STU</td>
		    		<td>CWX</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>40000</td>
	    		</tr>
	    		<tr>
		    		<td>5</td>
		    		<td>YZ</td>
		    		<td>ABC</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>15000</td>
	    		</tr><tr>
		    		<td>1</td>
		    		<td>ABC</td>
		    		<td>DEF</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>70000</td>
	    		</tr>
	    		<tr>
		    		<td>2</td>
		    		<td>GHI</td>
		    		<td>JKL</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>90000</td>
	    		</tr>
	    		<tr>
		    		<td>3</td>
		    		<td>MNO</td>
		    		<td>PQR</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>7000</td>
	    		</tr>
	    		<tr>
		    		<td>4</td>
		    		<td>STU</td>
		    		<td>CWX</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>40000</td>
	    		</tr>
	    		<tr>
		    		<td>5</td>
		    		<td>YZ</td>
		    		<td>ABC</td>
		    		<td>85</td>
		    		<td>70</td>
		    		<td>15000</td>
	    		</tr>
    		</tbody>
    	</table>
    </body>
    <!-- <script type="text/javascript" src="assets/js/bootstrap.min.js"></script> -->

    <script type="text/javascript" src="assets/js/jQuery.js"></script>
    <script type="text/javascript" src="assets/js/jQueryDatatables.js"></script>
    <script type="text/javascript">
		$(document).ready( function (){
			$("#empTable").DataTable({
				"language" : {
					"lengthMenu" : "Display _MENU_ records per page",
					"zeroRecords" : "No Records Found",
					"info" : "Showing page _PAGE_ of _PAGES_",
					"infoFiltered" : "(Filtered From _MAX_ total records)"
				}
			});
		});
	</script>
</html>